# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb_sequel}
  s.version = "1.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wayne E. Seguin", "Lance Carlson", "Lori Holden", "Pavel Kunc"]
  s.date = %q{2009-11-10}
  s.description = %q{Merb plugin that provides support for Sequel}
  s.email = %q{wayneeseguin@gmail.com, lancecarlson@gmail.com, email@loriholden.com, pavel.kunc@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "Generators",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "lib/generators/migration.rb",
     "lib/generators/model.rb",
     "lib/generators/resource_controller.rb",
     "lib/generators/session_migration.rb",
     "lib/generators/templates/migration/schema/migrations/%file_name%.rb",
     "lib/generators/templates/model/app/models/%file_name%.rb",
     "lib/generators/templates/resource_controller/app/controllers/%file_name%.rb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/edit.html.erb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/index.html.erb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/new.html.erb",
     "lib/generators/templates/resource_controller/app/views/%file_name%/show.html.erb",
     "lib/generators/templates/session_migration/schema/migrations/%version%_sessions.rb",
     "lib/merb/orms/sequel/connection.rb",
     "lib/merb/orms/sequel/database.yml.sample",
     "lib/merb/orms/sequel/model.rb",
     "lib/merb/session/sequel_session.rb",
     "lib/merb_sequel.rb",
     "lib/merb_sequel/merbtasks.rb",
     "lib/merb_sequel/rspec/sequel.rb",
     "lib/merb_sequel/version.rb",
     "spec/config/database.yml",
     "spec/log/merb_test.log",
     "spec/log/test.log",
     "spec/merb_sequel_session_spec.rb",
     "spec/merb_sequel_spec.rb",
     "spec/rspec/sequel_spec.rb",
     "spec/sequel_ext_spec.rb",
     "spec/spec.opts",
     "spec/spec_controller.rb",
     "spec/spec_helper.rb",
     "spec/spec_model.rb",
     "spec/test.db"
  ]
  s.homepage = %q{http://github.com/merb/merb_sequel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Merb plugin that provides support for Sequel}
  s.test_files = [
    "spec/merb_sequel_session_spec.rb",
     "spec/merb_sequel_spec.rb",
     "spec/rspec/sequel_spec.rb",
     "spec/sequel_ext_spec.rb",
     "spec/spec_controller.rb",
     "spec/spec_helper.rb",
     "spec/spec_model.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-core>, [">= 0.9.9"])
      s.add_runtime_dependency(%q<sequel>, [">= 2.7.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<merb-core>, [">= 0.9.9"])
      s.add_dependency(%q<sequel>, [">= 2.7.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<merb-core>, [">= 0.9.9"])
    s.add_dependency(%q<sequel>, [">= 2.7.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

